### ISSUE TITLE
Autocart

### ISSUE THREAD

**Issue by aoananp** [Paulowarren31/Supreme-Bot#48]
Hello Paulo,

The autocart feature does not work anymore, even on version 3.22
Tried adding a XL Jacket and it does not parse the size selector field and it does not auto click the Add to  Cart button.

Thanks in advance for all your work!

**Comment by Paulowarren31** [comment]
Could you give me the name of the item?

**Comment by aoananp** [comment]
http://www.supremenewyork.com/shop/jackets/az38de15p/hmi84jkuw
I try to cart this on an XL, but it wouldn't.
I think the identifier you used "select size" was removed from the page.
Thus, it detects that there is no size selection needed.
The selector also does not change to Large or XLarge.
And it still does not cart even the Small (first option).
Even the accessories will not cart.

**Comment by aoananp** [comment]
Whoops! Now it works! Thank you.

**Comment by Paulowarren31** [comment]
Pushed an update last night!

On Nov 8, 2017 7:22 AM, "aoananp" <notifications@github.com> wrote:

Whoops! Now it works! Thank you.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Paulowarren31/Supreme-Bot/issues/48#issuecomment-342802045>,
or mute the thread
