### ISSUE TITLE
Item Codes

### ISSUE THREAD

**Issue by HypePickups** [Paulowarren31/Supreme-Bot#65]
hey this isn't really a problem Im new to python programming and im also building a supreme bot of my own and im having trouble reading your code and understanding it. I was wondering if you or anyone else could provide me with a Python script on how to get the bot to find the items using the iteam codes please help man I would really apreciate it

**Comment by HypePickups** [comment]
found out how lol

**Comment by Paulowarren31** [comment]
Nice

On Mar 4, 2018 5:45 PM, "HypePickups" <notifications@github.com> wrote:

found out how lol

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Paulowarren31/Supreme-Bot/issues/65#issuecomment-370271455>,
or mute the thread
